services:
  mysql:
    image: mysql:8.1
    cap_add:
      - SYS_NICE
    volumes:
      - tiers:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", 'mysql --database=$$MYSQL_DATABASE --password=$$MYSQL_ROOT_PASSWORD --execute="SELECT count(table_name) > 0 FROM information_schema.tables;" --skip-column-names -B']
      interval: 2s
      timeout: 10s
      retries: 4
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tiers

  app:
    pid: "host"
    image: golang:1.21.0-alpine3.18
    command: sh -c "go build -o /usr/local/bin/app && app"
    ports:
      - 4000:4000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: tiers
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  tiers:
